spring:
  application:
    name: bot-exchanges
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0

  #  datasource:
  #    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  #    username: sa
  #    password:
  #    driver-class-name: org.h2.Driver
  #    platform: h2
  #    h2:
  #      console:
  #        enabled: true
  #        path: /h2

  datasource:
    url: jdbc:mysql://localhost:3306/bot_exchanges?autoReconnect=true&useUnicode=true&serverTimezone=UTC&useLegacyDatetimeCode=false&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: adminadmin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        #        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 8085

eureka:
  client:
    enabled: false

logging:
  level:
    root: WARN

feign:
  client:
    config:
      default:
        retryer: com.bot.exchanges.commons.utils.CustomRetryer

exchanges:
  bittrex:
    period:
      oneMin: oneMin
      fiveMin: fiveMin
      fifteenMin:
      thirdMin: thirtyMin
      oneHour: hour
    baseUrl: https://api.bittrex.com/api/v1.1
    baseUrl_2_0: https://bittrex.com/Api/v2.0
    apis:
      getTicker: /public/getticker?market={market}
      getMarkets: /public/getmarkets
      getTicks: /pub/market/GetTicks?tickInterval={tickInterval}&marketName={marketName}
      getOpenOrders: /market/getopenorders?market={market}
      getBalances: /account/getbalances
      getOpenHistory: /account/getorderhistory?market={market}
  binance:
    period:
      oneMin: 1m
      fiveMin: 5m
      fifteenMin: 15m
      thirdMin: 30m
      oneHour: 1h
    baseUrl: https://api.binance.com
    apis:
      klines: /api/v1/klines?symbol={symbol}&interval={interval}&startTime={startTime}&endTime={endTime}&limit={limit}
      exchangeInfo: /api/v1/exchangeInfo
      myTrades: /api/v3/myTrades?symbol={symbol}&startTime={startTime}&endTime={endTime}&fromId={fromId}&limit={limit}&recvWindow={recvWindow}&timestamp={timestamp}
  cryptocompare:
    period:
      oneMin: 1
      fiveMin: 5
      fifteenMin: 15
      thirdMin: 30
      oneHour: 60
    baseUrl: https://min-api.cryptocompare.com
    apis:
      coinList: /data/all/coinlist
      histoMinute: /data/histominute?fsym={fsym}&tsym={tsym}&limit={limit}&e={e}&aggregate={aggregate}&tryConversion={tryConversion}
      histoHour: /data/histoHour?fsym={fsym}&tsym={tsym}&limit={limit}&e={e}&aggregate={aggregate}&tryConversion={tryConversion}
  alphavantage:
    period:
      oneMin: 1min
      fiveMin: 5min
      fifteenMin: 15min
      thirdMin: 30min
      oneHour: 60min
    baseUrl: https://www.alphavantage.co
    apis:
      getTicks: /query?function={function}&symbol={symbol}&interval={interval}