spring:
  application:
    name: bot-schedule
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    enabled: false

logging:
  level:
    root: WARN

exchanges:
  baseUrl: http://localhost:8085
  apis:
    candlestick:
      basePath: /candlestick
      refreshLatestCandlestick: /refreshLatestCandlestick?exchangeEnum={exchangeEnum}&baseProductId={baseProductId}&productId={productId}&periodEnum={periodEnum}
    strategy:
      basePath: /strategy
      analyze: /analyze?exchangeEnum={exchangeEnum}&baseProductId={baseProductId}&productId={productId}&periodEnum={periodEnum}
      monitoring: /monitoring?exchangeEnum={exchangeEnum}
    exchangeProduct:
      basePath: /exchangeProduct
      findByExchangeId: /findByExchangeId?exchangeEnum={exchangeEnum}
    product:
      basePath: /product
      refreshProductList: /refreshProductList
  binance:
    schedules:
      active: true
  bittrex:
    schedules:
      active: true